version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./.docker-data/postgres:/var/lib/postgresql/data

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/shop_opening_hours
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
